seed: 1

# Paras for training feature embedding
label_dir: <path>
data_file: <path>
has_label: True
sample_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
train_names: [samples]
val_names: [samples]
test_names: [samples]
num_worker: [samples]

## ResNet parameters
out_classes: 7
class_weights: [0.0124, 0.2985, 0.3994, 0.0615, 0.1233, 0.0109, 0.0939]
#class_weights: [0.00530717, 0.21735648, 0.20511105, 0.45509013, 0.06331689, 0.0055968, 0.04822147]
start_iter: none
resnet_lr: 5e-4
resnet_momentum: 0.9
resnet_weight_decay: 0
resnet_iterations: 8000
resnet_train_bs: 128
resnet_decay_steps: [6000]
save_model: <path>
resnet_model: <path>
emb_file: <path>


## Fusion-transformer parametres
seq: 1024
fusion_iter: none
fusion_model: <path>
trans_lr: 1e-2
trans_weight_decay: 5e-3
trans_iterations: 4000
trans_steps: [1500, 2500]
trans_seq: 30
trans_bs: 1
trans_model: <path>
pred_folder: <path>
trans_iter: none